export const NuclearesPaths: { [key: string]: (string | number)[] } = {
	CORE_TEMP: ["core", "temp", "current"],
	CORE_TEMP_OPERATIVE: ["core", "temp", "operative"],
	CORE_TEMP_MAX: ["core", "temp", "max"],
	CORE_TEMP_MIN: ["core", "temp", "min"],
	CORE_TEMP_RESIDUAL: ["core", "temp", "residual"],
	CORE_PRESSURE: ["core", "pressure", "current"],
	CORE_PRESSURE_MAX: ["core", "pressure", "max"],
	CORE_PRESSURE_OPERATIVE: ["core", "pressure", "operative"],
	CORE_INTEGRITY: ["core", "integrity"],
	CORE_WEAR: ["core", "wear"],
	CORE_STATE: ["core", "reactive"],
	CORE_STATE_CRITICALITY: ["core", "stateCriticality"],
	CORE_CRITICAL_MASS_REACHED: ["core", "criticalMassReached"],
	CORE_CRITICAL_MASS_REACHED_COUNTER: ["core", "criticalMassReachedCounter"],
	CORE_IMMINENT_FUSION: ["core", "imminentFusion"],
	CORE_READY_FOR_START: ["core", "readyForStart"],
	CORE_STEAM_PRESENT: ["core", "steamPresent"],
	CORE_HIGH_STEAM_PRESENT: ["core", "highSteamPresent"],
	TIME: ["time", "time"],
	TIME_STAMP: ["time", "timestamp"],
	COOLANT_CORE_STATE: ["coolant", "circulating"],
	COOLANT_CORE_PRESSURE: ["coolant", "pressure"],
	COOLANT_CORE_MAX_PRESSURE: ["coolant", "maxPressure"],
	COOLANT_CORE_VESSEL_TEMPERATURE: ["coolant", "vesselTemperature"],
	COOLANT_CORE_QUANTITY_IN_VESSEL: ["coolant", "quantityInVessel"],
	COOLANT_CORE_PRIMARY_LOOP_LEVEL: ["coolant", "primaryLoopLevel"],
	COOLANT_CORE_FLOW_SPEED: ["coolant", "flowSpeed"],
	COOLANT_CORE_FLOW_ORDERED_SPEED: ["coolant", "orderedFlowSpeed"],
	COOLANT_CORE_FLOW_REACHED_SPEED: ["coolant", "reachedFlowSpeed"],
	COOLANT_CORE_QUANTITY_CIRCULATION_PUMPS_PRESENT: [
		"coolant",
		"quantityCirculationPumpsPresent",
	],
	COOLANT_CORE_QUANTITY_FREIGHT_PUMPS_PRESENT: [
		"coolant",
		"quantityFreightPumpsPresent",
	],
	COOLANT_CORE_CIRCULATION_PUMP_0_STATUS: ["coolant", "pumps", 0, "status"],
	COOLANT_CORE_CIRCULATION_PUMP_1_STATUS: ["coolant", "pumps", 1, "status"],
	COOLANT_CORE_CIRCULATION_PUMP_2_STATUS: ["coolant", "pumps", 2, "status"],
	COOLANT_CORE_CIRCULATION_PUMP_0_DRY_STATUS: [
		"coolant",
		"pumps",
		0,
		"dryStatus",
	],
	COOLANT_CORE_CIRCULATION_PUMP_1_DRY_STATUS: [
		"coolant",
		"pumps",
		1,
		"dryStatus",
	],
	COOLANT_CORE_CIRCULATION_PUMP_2_DRY_STATUS: [
		"coolant",
		"pumps",
		2,
		"dryStatus",
	],
	COOLANT_CORE_CIRCULATION_PUMP_0_OVERLOAD_STATUS: [
		"coolant",
		"pumps",
		0,
		"overloadStatus",
	],
	COOLANT_CORE_CIRCULATION_PUMP_1_OVERLOAD_STATUS: [
		"coolant",
		"pumps",
		1,
		"overloadStatus",
	],
	COOLANT_CORE_CIRCULATION_PUMP_2_OVERLOAD_STATUS: [
		"coolant",
		"pumps",
		2,
		"overloadStatus",
	],
	COOLANT_CORE_CIRCULATION_PUMP_0_ORDERED_SPEED: [
		"coolant",
		"pumps",
		0,
		"orderedSpeed",
	],
	COOLANT_CORE_CIRCULATION_PUMP_1_ORDERED_SPEED: [
		"coolant",
		"pumps",
		1,
		"orderedSpeed",
	],
	COOLANT_CORE_CIRCULATION_PUMP_2_ORDERED_SPEED: [
		"coolant",
		"pumps",
		2,
		"orderedSpeed",
	],
	COOLANT_CORE_CIRCULATION_PUMP_0_SPEED: ["coolant", "pumps", 0, "speed"],
	COOLANT_CORE_CIRCULATION_PUMP_1_SPEED: ["coolant", "pumps", 1, "speed"],
	COOLANT_CORE_CIRCULATION_PUMP_2_SPEED: ["coolant", "pumps", 2, "speed"],
	RODS_STATUS: ["rods", "status"],
	RODS_MOVEMENT_SPEED: ["rods", "movementSpeed"],
	RODS_MOVEMENT_SPEED_DECREASED_HIGH_TEMPERATURE: [
		"rods",
		"movementSpeedDecreasedHighTemp",
	],
	RODS_DEFORMED: ["rods", "deformed"],
	RODS_TEMPERATURE: ["rods", "temperature"],
	RODS_MAX_TEMPERATURE: ["rods", "maxTemperature"],
	RODS_POS_ORDERED: ["rods", "posOrdered"],
	RODS_POS_ACTUAL: ["rods", "posActual"],
	RODS_POS_REACHED: ["rods", "posReached"],
	RODS_QUANTITY: ["rods", "quantity"],
	RODS_ALIGNED: ["rods", "aligned"],
	GENERATOR_0_KW: ["generators", "turbine", 0, "kw"],
	GENERATOR_1_KW: ["generators", "turbine", 1, "kw"],
	GENERATOR_2_KW: ["generators", "turbine", 2, "kw"],
	GENERATOR_0_V: ["generators", "turbine", 0, "v"],
	GENERATOR_1_V: ["generators", "turbine", 1, "v"],
	GENERATOR_2_V: ["generators", "turbine", 2, "v"],
	GENERATOR_0_A: ["generators", "turbine", 0, "a"],
	GENERATOR_1_A: ["generators", "turbine", 1, "a"],
	GENERATOR_2_A: ["generators", "turbine", 2, "a"],
	GENERATOR_0_HERTZ: ["generators", "turbine", 0, "hertz"],
	GENERATOR_1_HERTZ: ["generators", "turbine", 1, "hertz"],
	GENERATOR_2_HERTZ: ["generators", "turbine", 2, "hertz"],
	GENERATOR_0_BREAKER: ["generators", "turbine", 0, "breaker"],
	GENERATOR_1_BREAKER: ["generators", "turbine", 1, "breaker"],
	GENERATOR_2_BREAKER: ["generators", "turbine", 2, "breaker"],
	STEAM_TURBINE_0_RPM: ["turbines", "turbines", 0, "rpm"],
	STEAM_TURBINE_1_RPM: ["turbines", "turbines", 1, "rpm"],
	STEAM_TURBINE_2_RPM: ["turbines", "turbines", 2, "rpm"],
	STEAM_TURBINE_0_TEMPERATURE: ["turbines", "turbines", 0, "temperature"],
	STEAM_TURBINE_1_TEMPERATURE: ["turbines", "turbines", 1, "temperature"],
	STEAM_TURBINE_2_TEMPERATURE: ["turbines", "turbines", 2, "temperature"],
	STEAM_TURBINE_0_PRESSURE: ["turbines", "turbines", 0, "pressure"],
	STEAM_TURBINE_1_PRESSURE: ["turbines", "turbines", 1, "pressure"],
	STEAM_TURBINE_2_PRESSURE: ["turbines", "turbines", 2, "pressure"],
};
